-- require("lualine").setup({
--     optional = true,
--     opts = function(_,opts)
--         table.insert(opts.sections.lualine_x, {
--           function()
--             local status = require("ollama").status()

--             if status == "IDLE" then
--                 return "IDLE"
--               -- return "󱙺" -- nf-md-robot-outline
--             elseif status == "WORKING" then
--                 return "WORKING"
--               -- return "󰚩" -- nf-md-robot
--             end
--           end,
--           cond = function()
--             return package.loaded["ollama"] and require("ollama").status() ~= nil
--           end,
--         })
--     end,
-- })
