require("terminalPoltergeist.options")
require("terminalPoltergeist.remaps")
require("terminalPoltergeist.autocmd")
require("terminalPoltergeist.packer")
require("terminalPoltergeist.colors")
vim.cmd("source ~/.config/nvim/lua/terminalPoltergeist/functions.vim")
