local o = vim.o

-- o.guicursor = ""
o.expandtab = true
o.wrap = false
o.shiftwidth = 4
o.tabstop = 4
o.hidden = true
o.mouse = 'a'
o.scrolloff = 8
o.sidescrolloff = 6
o.relativenumber = true
o.number = true
o.confirm = true
o.cursorline = true
o.autoindent = true
o.cmdheight = 1
o.updatetime = 300
o.linebreak = true
o.swapfile = false
o.incsearch = true
o.termguicolors = true
o.clipboard = "unnamedplus"
o.foldmethod = "expr"
o.foldexpr = "v:lua.vim.treesitter.foldexpr()"
o.foldlevel = 100 -- fold any region containing more than 100 lines
o.foldminlines = 4
-- o.winborder = 'rounded'
